#release configuration
#Tue Dec 19 13:48:50 EET 2023
scm.tagNameFormat=@{project.artifactId}-@{project.version}
pushChanges=true
scm.url=scm\:git\:git@github.com\:jenkinsci/hp-application-automation-tools-plugin.git
preparationGoals=clean install
remoteTagging=true
projectVersionPolicyId=default
scm.commentPrefix=[maven-release-plugin] 
completionGoals=incrementals\:reincrementalify
exec.snapshotReleasePluginAllowed=false
exec.additionalArguments=-DskipTests -P artifactory,nexus,consume-incrementals,might-produce-incrementals
completedPhase=check-poms
